//
// Created by christianb on 19.07.20.
//

#ifndef RTSP_PARSER_RTSP_INTERNAL_H
#define RTSP_PARSER_RTSP_INTERNAL_H

#include "rtsp_types.h"

typedef enum {
    RTSP_TYPE_UNKNOWN,
    RTSP_TYPE_REQUEST,
    RTSP_TYPE_RESPONSE
} eRTSP_TYPE;

typedef enum {
    RTSP_VERSION_UNKNOWN,
    RTSP_VERSION_UNSUPPORTED,
    RTSP_VERSION_1_0
} eRTSP_VERSION;

const char * rtsp_internal_header_to_string(eRTSP_HEADER h);
const char * rtsp_internal_method_to_string(eRTSP_METHOD m);

//Version strings
extern const char * cRTSP_INTERNAL_VERSION_1_0;
extern const char * cRTSP_INTERNAL_VERSION_2_0;

//Methods
const char * cRTSP_INTERNAL_METHOD_DESCRIBE;
const char * cRTSP_INTERNAL_METHOD_ANNOUNCE;
const char * cRTSP_INTERNAL_METHOD_GET_PARAMETER;
const char * cRTSP_INTERNAL_METHOD_OPTIONS;
const char * cRTSP_INTERNAL_METHOD_PAUSE;
const char * cRTSP_INTERNAL_METHOD_PLAY;
const char * cRTSP_INTERNAL_METHOD_RECORD;
const char * cRTSP_INTERNAL_METHOD_REDIRECT;
const char * cRTSP_INTERNAL_METHOD_SETUP;
const char * cRTSP_INTERNAL_METHOD_SET_PARAMETER;
const char * cRTSP_INTERNAL_METHOD_TEARDOWN;

//Known header strings
const char * cRTSP_INTERNAL_HEADER_CACHE_CONTROL;
const char * cRTSP_INTERNAL_HEADER_CONNECTION;
const char * cRTSP_INTERNAL_HEADER_DATE;
const char * cRTSP_INTERNAL_HEADER_VIA;
const char * cRTSP_INTERNAL_HEADER_ACCEPT;
const char * cRTSP_INTERNAL_HEADER_ACCEPT_ENCODING;
const char * cRTSP_INTERNAL_HEADER_ACCEPT_LANGUAGE;
const char * cRTSP_INTERNAL_HEADER_AUTHORIZATION;
const char * cRTSP_INTERNAL_HEADER_FROM;
const char * cRTSP_INTERNAL_HEADER_IF_MODIFIED_SINCE;
const char * cRTSP_INTERNAL_HEADER_RANGE;
const char * cRTSP_INTERNAL_HEADER_REFERER;
const char * cRTSP_INTERNAL_HEADER_USER_AGENT;
const char * cRTSP_INTERNAL_HEADER_LOCATION;
const char * cRTSP_INTERNAL_HEADER_PROXY_AUTHENTICATE;
const char * cRTSP_INTERNAL_HEADER_PUBLIC;
const char * cRTSP_INTERNAL_HEADER_RETRY_AFTER;
const char * cRTSP_INTERNAL_HEADER_SERVER;
const char * cRTSP_INTERNAL_HEADER_VARY;
const char * cRTSP_INTERNAL_HEADER_WWW_AUTHENTICATE;
const char * cRTSP_INTERNAL_HEADER_ALLOW;
const char * cRTSP_INTERNAL_HEADER_CONTENT_BASE;
const char * cRTSP_INTERNAL_HEADER_CONTENT_ENCODING;
const char * cRTSP_INTERNAL_HEADER_CONTENT_LANGUAGE;
const char * cRTSP_INTERNAL_HEADER_CONTENT_LENGTH;
const char * cRTSP_INTERNAL_HEADER_CONTENT_LOCATION;
const char * cRTSP_INTERNAL_HEADER_CONTENT_TYPE;
const char * cRTSP_INTERNAL_HEADER_EXPIRES;
const char * cRTSP_INTERNAL_HEADER_LAST_MODIFIED;
const char * cRTSP_INTERNAL_HEADER_BANDWITH;
const char * cRTSP_INTERNAL_HEADER_BLOCKSIZE;
const char * cRTSP_INTERNAL_HEADER_CONFERENCE;
const char * cRTSP_INTERNAL_HEADER_CSEQ;
const char * cRTSP_INTERNAL_HEADER_HOST;
const char * cRTSP_INTERNAL_HEADER_IF_MATCH;
const char * cRTSP_INTERNAL_HEADER_PROXY_REQUIRE;
const char * cRTSP_INTERNAL_HEADER_REQUIRE;
const char * cRTSP_INTERNAL_HEADER_RTP_INFO;
const char * cRTSP_INTERNAL_HEADER_SCALE;
const char * cRTSP_INTERNAL_HEADER_SPEED;
const char * cRTSP_INTERNAL_HEADER_SESSION;
const char * cRTSP_INTERNAL_HEADER_TIMESTAMP;
const char * cRTSP_INTERNAL_HEADER_TRANSPORT;
const char * cRTSP_INTERNAL_HEADER_UNSUPPORTED;

#endif //RTSP_PARSER_RTSP_INTERNAL_H
